# It's just an example. Typical unix config file.

# speed can be one of the following value: 
speed = 4800

# stopbit
stopbit=  two # я дурачок

# paritybit
paritybit  =mark

# databits. If fact it sets how many bits is reserved in frame for
#   data (payload).
databits = 8

# inputparitycheck.  I'm not sure it works fine
# disable, enable_ignore, enable_mark
inputparitycheck = disable